language: python

# sudo false implies containerized builds, so we can use cacheing
sudo: false

deploy:
  provider: pypi
  user: andreas.mayer
  password:
    secure: Muws+2oiSf4TM40LE+uhPq1PcX8jiN3TsNEFuqaccIWQCBId7RHCj620TWqDoBQNSb9BIlokVCx+nEewmQ4yzwUpQwx8FguRAJnkTNcwNJZquF4kmVJ4iyAxH/EDn2MikZU3RqA8NVqqda+eZBV9L1YbrZ5z+g9RhDr8U4PmqIlv6Cnu3lGmWt8pcL91RMkMJYDw6hKl1XS5Ghe/Ukqa+wmYwPwteCZFx9xsgSmVRDKgS0ycXdtDuoc0ewO4UWgDooMB7DKcHCWhIpYRDRxCJkGHQ4I5L6SrIF4fPtiz2pY9nNDoOHLdLfUSIjFA5X5AtIzdNbtbOIfFn9h11y1eaHXoqWibbfG49N4HR9U5sdHy03IgBE1SVejP0UF0z1F4WJh6cf3QC8XYWcZgYtNGFUUM/xsel6HCZ9xDjPx2T2NyeeCGEnMkkafBhwZBYgm+KhTy+404pDaqZYknN89jyYNJ9K72zyM4oCV643ubCU3yLfiZml7oWc7/Ui9eiGXDky2Tqv6gF420LQZTBKlcdmTcLj6trcC/SZhKU3rIqaJTaRNMHmfAF2YTBlo3OExthZyN1PKWeqjmt9wDXhQHB+S/QCnGnJMj5VkQLkvIRWS5HpB74MdEL4IjDfEyf/XnPmdXzMWqon+jjBoM7vOYA3BL6zr4C3aq1MLIdXiO6OI=
  distributions: "sdist bdist_wheel"
  on:
    tags: true

python:
- 2.7
- 3.5
- 3.6

addons:
    apt:
        packages:
# fortran needed for direct compilation
            - gfortran

env:
  - CONDA_DEPS="pip pytest numpy scipy" PIP_DEPS="coveralls"

before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- command -v conda >/dev/null || { if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  else
    wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  fi;
  bash miniconda.sh -b -f -p $MINICONDA; }
- conda config --set always_yes yes
- conda update conda
- conda info -a

install:
- conda install python=$TRAVIS_PYTHON_VERSION $CONDA_DEPS
- conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements.txt
- travis_retry pip install $PIP_DEPS
- python setup.py install --record installed_files.txt

script:
- py.test

after_success:
- coveralls

before_cache:
# clean unused packages & installed files from conda cache
# this makes the cache rebuilt less frequently
- conda clean --tarballs --packages --index-cache
- rm -rf $HOME/miniconda/pkgs/cache
- xargs rm <installed_files.txt

cache:
  directories:
    - $HOME/miniconda
