language: python

addons:
    apt:
        packages:
            # fortran needed for direct compilation
            - gfortran
  
install:
- pip install -r requirements.txt
- pip install .

script:
- pytest

deploy:
  provider: pypi
  user: andreas.mayer
  password:
    secure: "KqdVvhA/JZjTx+ZPgH2a++c5Vs9hWuuvRy+KhcYPAN7yjvYoUH9exZwjy56Lm38b5EyH2txS4Ht6ShLc/GAa1m4YIHmSn6kdc21CVZqvBk9Jb5lClg+NF2M6gkY3/TPfuFXUvTh6Hoa4gy/o/Wi783PyvxidueER02NbLQMW10zobfnLGOpNyDFZRRhP+2hyRvrfcFzNS9Q6oJNWvXPAyE3Bp4zTTf5IM4k5gibekf8MsO+bSoNuLGb8AljIacN453FZLQKgj0wWuXxd3K9PWm5ghR5WsNULHGCyA7M6KvrN0CZfZv5e6rtPx/BNr+IevVGzVr+Sefq22SYHbfFjXkp+GClycd3L1XGuQPo0HinPgVkzSmlffgOiEoxcHmcbJNaWCSrapCopTB+igk2JKtLPAliZG1cJu99klivrmIaydwvBo80kbFYauvrFDT57Z8GLOeKV3atLntL7A0dJ2iQKhb1glG27gpg99fzzFGmkFNncdmlz5V1aHtLXt5B7ki1W3OWeBnv8Nkz4wP4tWHAsE23EFZYG+Vn+sqZqiuZS0YOoKGjF3PnE7LbGpUBs2jLbj2RCzSYqKYyW4OYZKCKrpU3Fm86ssmZ9Fn87ZeXK4pirjD3C034hGmm3T8UnOHTq3XizAscAd6Jn6243EW+Cn1hBa6bpC8g9X7aeW+o="
  distributions: "sdist"
  on:
    tags: true

